unit TesteUnitario;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, uProduto;

type
  // Test methods for class TProduto

  TestTProduto = class(TTestCase)
  strict private
    FProduto: TProduto;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestcalcularDesconto;
  end;

implementation

procedure TestTProduto.SetUp;
begin
  FProduto := TProduto.Create;
end;

procedure TestTProduto.TearDown;
begin
  FProduto.Free;
  FProduto := nil;
end;

procedure TestTProduto.TestcalcularDesconto;
var
  ReturnValue: Double;
  xQtd: Integer;
  xValor: double;
begin
  FProduto.Quantidade := 51;
  FProduto.PrecoUnitario := 10;

  ReturnValue := FProduto.calcularDesconto;
  // TODO: Validate method results
  CheckEquals(382.5, ReturnValue, 'Erro ao calcular desconto!');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTProduto.Suite);
end.

